/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    MarkdownRenderer: typeof import('./components/MarkdownRenderer.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
  }
}
